name: Build & Deploy to S3

on:
  push:
    branches: [ main ]
    paths:
      - 'www/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: www

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: www/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::927414202992:role/GithubActionsDeployRole   # <- from output
          aws-region: ca-central-1

      - name: Upload assets (immutable)
        run: |
          aws s3 sync dist s3://${{ vars.S3_BUCKET }} \
            --exclude "*.html" \
            --exclude "robots.txt" " --exclude "sitemap.xml" \
            --exclude "manifest.json" --exclude "service-worker.js" --exclude "sw.js" \
            --cache-control "public, max-age=31536000, immutable" --delete

      - name: Upload HTML (no-cache)
        run: |
          aws s3 sync dist s3://${{ vars.S3_BUCKET }} \
            --exclude "*" --include "*.html" \
            --cache-control "public, max-age=0, no-cache, no-store, must-revalidate" --delete

      - name: Upload special files (no-cache)
        run: |
          for f in robots.txt sitemap.xml manifest.json service-worker.js sw.js; do
            if [ -f "dist/$f" ]; then
              aws s3 cp "dist/$f" "s3://${{ vars.S3_BUCKET }}/$f" \
                --cache-control "public, max-age=0, no-cache, no-store, must-revalidate"
            fi
          done

      - name: Invalidate CloudFront
        if: ${{ vars.CF_DISTRIBUTION_ID != '' }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CF_DISTRIBUTION_ID }} \
            --paths "/" "/index.html"